const flashcards = [
    {id: 1, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 2, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 3, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 4, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 5, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 6, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 7, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 8, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 9, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 10, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 11, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 12, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 13, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 14, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 15, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 16, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 17, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 18, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 19, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 20, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 21, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 22, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 23, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 24, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 25, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 26, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 27, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 28, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 29, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 30, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 31, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 32, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 33, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 34, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 35, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 36, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 37, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 38, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 39, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 40, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 41, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 42, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 43, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 44, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 45, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 46, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 47, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 48, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 49, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 50, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 51, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 52, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 53, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 54, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 55, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 56, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek."},
    {id: 57, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka."},
    {id: 58, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek."},
    {id: 59, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przecinka."},
    {id: 60, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przecinka."},
    {id: 61, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 62, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 63, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 64, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 65, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 66, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 67, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 68, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 69, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 70, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 71, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 72, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 73, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 74, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 75, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 76, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 77, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 78, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 79, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 80, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 81, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 82, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 83, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 84, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 85, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 86, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 87, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 88, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 89, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 90, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 91, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 92, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 93, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 94, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 95, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 96, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 97, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 98, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 99, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 100, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 101, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 102, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 103, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 104, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 105, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 106, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 107, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 108, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 109, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 110, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 111, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 112, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 113, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 114, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 115, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 116, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó→O (stół→stołu)."},
    {id: 117, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó→O (wóz→wozu)."},
    {id: 118, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó→O/A (góra→gary)."},
    {id: 119, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany."},
    {id: 120, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany."},
    {id: 121, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 122, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 123, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 124, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 125, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 126, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 127, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 128, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 129, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 130, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 131, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 132, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 133, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 134, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 135, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 136, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 137, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 138, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 139, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 140, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 141, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 142, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 143, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 144, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 145, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 146, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 147, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 148, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 149, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 150, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 151, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 152, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 153, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 154, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 155, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 156, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 157, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 158, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 159, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 160, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 161, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 162, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 163, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 164, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 165, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 166, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 167, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 168, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 169, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 170, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 171, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 172, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 173, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 174, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 175, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 176, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P→RZ."},
    {id: 177, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B→RZ."},
    {id: 178, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)."},
    {id: 179, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż→G (książka→księgi)."},
    {id: 180, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N→Ż."},
    {id: 181, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 182, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 183, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 184, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 185, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 186, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 187, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 188, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 189, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 190, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 191, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 192, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 193, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 194, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 195, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 196, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 197, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 198, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 199, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 200, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 201, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 202, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 203, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 204, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 205, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 206, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 207, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 208, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 209, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 210, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 211, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 212, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 213, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 214, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 215, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 216, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 217, category: "Ortografia ch/h", front: "Mu_a", back: "Mucha", rule: "CH→SZ (mucha→muszka)."},
    {id: 218, category: "Ortografia ch/h", front: "Suc_y", back: "Suchy", rule: "CH→SZ (suchy→susza)."},
    {id: 219, category: "Ortografia ch/h", front: "Bo_ater", back: "Bohater", rule: "H w wyrazach obcych."},
    {id: 220, category: "Ortografia ch/h", front: "_istoria", back: "Historia", rule: "H w wyrazach obcych."},
    {id: 221, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 222, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 223, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 224, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 225, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 226, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 227, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 228, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 229, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 230, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 231, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 232, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 233, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 234, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 235, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 236, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 237, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 238, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 239, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 240, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 241, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 242, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 243, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 244, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 245, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 246, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 247, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 248, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 249, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 250, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 251, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 252, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 253, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 254, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 255, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 256, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 257, category: "Pisownia 'nie'", front: "__ie wiem", back: "Nie wiem", rule: "Nie+czasownik→osobno."},
    {id: 258, category: "Pisownia 'nie'", front: "__ieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie."},
    {id: 259, category: "Pisownia 'nie'", front: "__ie lepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno."},
    {id: 260, category: "Pisownia 'nie'", front: "__ieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie."},
    {id: 261, category: "Rozprawka", front: "Moim zdan__em", back: "Moim zdaniem", rule: "Wyrażenie opinii."},
    {id: 262, category: "Rozprawka", front: "W _ogóle", back: "W ogóle", rule: "Pisownia rozdzielna."},
    {id: 263, category: "Rozprawka", front: "Na pe__no", back: "Na pewno", rule: "Pisownia rozdzielna."},
    {id: 264, category: "Rozprawka", front: "Konkluduj__c [?]", back: "Konkludując,", rule: "Imiesłów→przecinek."},
    {id: 265, category: "Rozprawka", front: "Moim zdan__em", back: "Moim zdaniem", rule: "Wyrażenie opinii."},
    {id: 266, category: "Rozprawka", front: "W _ogóle", back: "W ogóle", rule: "Pisownia rozdzielna."},
    {id: 267, category: "Rozprawka", front: "Na pe__no", back: "Na pewno", rule: "Pisownia rozdzielna."},
    {id: 268, category: "Rozprawka", front: "Konkluduj__c [?]", back: "Konkludując,", rule: "Imiesłów→przecinek."},
    {id: 269, category: "Rozprawka", front: "Moim zdan__em", back: "Moim zdaniem", rule: "Wyrażenie opinii."},
    {id: 270, category: "Rozprawka", front: "W _ogóle", back: "W ogóle", rule: "Pisownia rozdzielna."},
    {id: 271, category: "Rozprawka", front: "Na pe__no", back: "Na pewno", rule: "Pisownia rozdzielna."},
    {id: 272, category: "Rozprawka", front: "Konkluduj__c [?]", back: "Konkludując,", rule: "Imiesłów→przecinek."},
    {id: 273, category: "Rozprawka", front: "Moim zdan__em", back: "Moim zdaniem", rule: "Wyrażenie opinii."},
    {id: 274, category: "Rozprawka", front: "W _ogóle", back: "W ogóle", rule: "Pisownia rozdzielna."},
    {id: 275, category: "Rozprawka", front: "Na pe__no", back: "Na pewno", rule: "Pisownia rozdzielna."},
    {id: 276, category: "Rozprawka", front: "Konkluduj__c [?]", back: "Konkludując,", rule: "Imiesłów→przecinek."},
    {id: 277, category: "Rozprawka", front: "Moim zdan__em", back: "Moim zdaniem", rule: "Wyrażenie opinii."},
    {id: 278, category: "Rozprawka", front: "W _ogóle", back: "W ogóle", rule: "Pisownia rozdzielna."},
    {id: 279, category: "Rozprawka", front: "Na pe__no", back: "Na pewno", rule: "Pisownia rozdzielna."},
    {id: 280, category: "Rozprawka", front: "Konkluduj__c [?]", back: "Konkludując,", rule: "Imiesłów→przecinek."},
    {id: 281, category: "Opowiadanie", front: "Ni__st__d ni zow__d", back: "Ni stąd, ni zowąd", rule: "Wyrażenie frazeologiczne."},
    {id: 282, category: "Opowiadanie", front: "Wtem / W tym", back: "Wtem", rule: "'Wtem'=nagle."},
    {id: 283, category: "Opowiadanie", front: "Ni__st__d ni zow__d", back: "Ni stąd, ni zowąd", rule: "Wyrażenie frazeologiczne."},
    {id: 284, category: "Opowiadanie", front: "Wtem / W tym", back: "Wtem", rule: "'Wtem'=nagle."},
    {id: 285, category: "Opowiadanie", front: "Ni__st__d ni zow__d", back: "Ni stąd, ni zowąd", rule: "Wyrażenie frazeologiczne."},
    {id: 286, category: "Opowiadanie", front: "Wtem / W tym", back: "Wtem", rule: "'Wtem'=nagle."},
    {id: 287, category: "Opowiadanie", front: "Ni__st__d ni zow__d", back: "Ni stąd, ni zowąd", rule: "Wyrażenie frazeologiczne."},
    {id: 288, category: "Opowiadanie", front: "Wtem / W tym", back: "Wtem", rule: "'Wtem'=nagle."},
    {id: 289, category: "Opowiadanie", front: "Ni__st__d ni zow__d", back: "Ni stąd, ni zowąd", rule: "Wyrażenie frazeologiczne."},
    {id: 290, category: "Opowiadanie", front: "Wtem / W tym", back: "Wtem", rule: "'Wtem'=nagle."},
    {id: 291, category: "Wielka litera", front: "uniwersytet / Uniwersytet Warszawski", back: "Uniwersytet Warszawski", rule: "Nazwy własne→wielka."},
    {id: 292, category: "Wielka litera", front: "Wisła", back: "Wisła", rule: "Nazwy geograficzne→wielka."},
    {id: 293, category: "Wielka litera", front: "uniwersytet / Uniwersytet Warszawski", back: "Uniwersytet Warszawski", rule: "Nazwy własne→wielka."},
    {id: 294, category: "Wielka litera", front: "Wisła", back: "Wisła", rule: "Nazwy geograficzne→wielka."},
    {id: 295, category: "Wielka litera", front: "uniwersytet / Uniwersytet Warszawski", back: "Uniwersytet Warszawski", rule: "Nazwy własne→wielka."},
    {id: 296, category: "Wielka litera", front: "Wisła", back: "Wisła", rule: "Nazwy geograficzne→wielka."},
    {id: 297, category: "Wielka litera", front: "uniwersytet / Uniwersytet Warszawski", back: "Uniwersytet Warszawski", rule: "Nazwy własne→wielka."},
    {id: 298, category: "Wielka litera", front: "Wisła", back: "Wisła", rule: "Nazwy geograficzne→wielka."},
    {id: 299, category: "Wielka litera", front: "uniwersytet / Uniwersytet Warszawski", back: "Uniwersytet Warszawski", rule: "Nazwy własne→wielka."},
    {id: 300, category: "Wielka litera", front: "Wisła", back: "Wisła", rule: "Nazwy geograficzne→wielka."}
];

if (typeof module !== 'undefined') {
    module.exports = flashcards;
}
