const flashcards = [
    { id: 1, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' zawsze przecinek." },
    { id: 2, category: "Interpunkcja", front: "Mimo [?] że padało...", back: "Mimo że padało,", rule: "Cofanie przecinka przed 'mimo że'." },
    { id: 3, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ...", back: "Nie poszedłem, ponieważ", rule: "Przed 'ponieważ' przecinek." },
    { id: 4, category: "Interpunkcja", front: "Przyjdę [?] chyba że...", back: "Przyjdę, chyba że", rule: "Cofanie przed 'chyba że'." },
    { id: 5, category: "Interpunkcja", front: "Zrobię to [?] tylko że...", back: "Zrobię to, tylko że", rule: "Cofanie przed 'tylko że'." },
    { id: 6, category: "Interpunkcja", front: "Powiedział [?] że przyjdzie.", back: "Powiedział, że przyjdzie.", rule: "Przecinek przed 'że'." },
    { id: 7, category: "Interpunkcja", front: "Myślę [?] że to dobry pomysł.", back: "Myślę, że to dobry pomysł.", rule: "Przecinek przed 'że'." },
    { id: 8, category: "Interpunkcja", front: "Wiem [?] że masz rację.", back: "Wiem, że masz rację.", rule: "Przecinek przed 'że'." },
    { id: 9, category: "Interpunkcja", front: "Cieszę się [?] że przyszedłeś.", back: "Cieszę się, że przyszedłeś.", rule: "Przecinek przed 'że'." },
    { id: 10, category: "Interpunkcja", front: "Podczas [?] gdy on spał...", back: "Podczas gdy on spał,", rule: "Cofanie przed 'podczas gdy'." },
    { id: 11, category: "Interpunkcja", front: "Chociaż [?] był zmęczony...", back: "Chociaż był zmęczony,", rule: "Zdanie podrzędne na początku." },
    { id: 12, category: "Interpunkcja", front: "Jeśli [?] przyjdziesz...", back: "Jeśli przyjdziesz,", rule: "Zdanie warunkowe." },
    { id: 13, category: "Interpunkcja", front: "Kiedy [?] wrócisz, zadzwoń.", back: "Kiedy wrócisz, zadzwoń.", rule: "Zdanie czasu." },
    { id: 14, category: "Interpunkcja", front: "Ponieważ [?] padało...", back: "Ponieważ padało,", rule: "Zdanie przyczynowe." },
    { id: 15, category: "Interpunkcja", front: "Gdyby [?] wiedział...", back: "Gdyby wiedział,", rule: "Zdanie warunkowe." },
    { id: 16, category: "Interpunkcja", front: "Dlatego [?] że...", back: "Dlatego że...", rule: "Cofanie przed 'dlatego że'." },
    { id: 17, category: "Interpunkcja", front: "Jako [?] że...", back: "Jako że...", rule: "Cofanie przed 'jako że'." },
    { id: 18, category: "Interpunkcja", front: "Tym bardziej [?] że...", back: "Tym bardziej że...", rule: "Cofanie przecinka." },
    { id: 19, category: "Interpunkcja", front: "Aczkolwiek [?]", back: "Aczkolwiek,", rule: "Spójnik - przecinek." },
    { id: 20, category: "Interpunkcja", front: "Jednakże [?]", back: "Jednakże,", rule: "Spójnik - przecinek." },
    { id: 21, category: "Interpunkcja", front: "Jeżeli [?] przyjdziesz...", back: "Jeżeli przyjdziesz,", rule: "Zdanie warunkowe." },
    { id: 22, category: "Interpunkcja", front: "Zanim [?] wyjdziesz...", back: "Zanim wyjdziesz,", rule: "Zdanie czasu." },
    { id: 23, category: "Interpunkcja", front: "Dopóki [?] nie wrócisz...", back: "Dopóki nie wrócisz,", rule: "Zdanie czasu." },
    { id: 24, category: "Interpunkcja", front: "Odkąd [?] wyjechał...", back: "Odkąd wyjechał,", rule: "Zdanie czasu." },
    { id: 25, category: "Interpunkcja", front: "Skoro [?] tak mówisz...", back: "Skoro tak mówisz,", rule: "Zdanie przyczynowe." },
    { id: 26, category: "Interpunkcja", front: "Choć [?] był chory...", back: "Choć był chory,", rule: "Zdanie przyzwolenia." },
    { id: 27, category: "Interpunkcja", front: "Choćby [?] chciał...", back: "Choćby chciał,", rule: "Zdanie przyzwolenia." },
    { id: 28, category: "Interpunkcja", front: "Ażeby [?] było lepiej...", back: "Ażeby było lepiej,", rule: "Zdanie celowe." },
    { id: 29, category: "Interpunkcja", front: "Żeby [?] było jasne...", back: "Żeby było jasne,", rule: "Zdanie celowe." },
    { id: 30, category: "Interpunkcja", front: "Aby [?] zrozumieć...", back: "Aby zrozumieć,", rule: "Zdanie celowe." },
    { id: 31, category: "Interpunkcja", front: "Tak [?] że...", back: "Tak, że...", rule: "Przecinek przed 'że'." },
    { id: 32, category: "Interpunkcja", front: "Taki [?] że...", back: "Taki, że...", rule: "Przecinek przed 'że'." },
    { id: 33, category: "Interpunkcja", front: "Wtedy [?] gdy...", back: "Wtedy, gdy...", rule: "Przecinek przed 'gdy'." },
    { id: 34, category: "Interpunkcja", front: "Tam [?] gdzie...", back: "Tam, gdzie...", rule: "Przecinek przed 'gdzie'." },
    { id: 35, category: "Interpunkcja", front: "Taki [?] jaki...", back: "Taki, jaki...", rule: "Przecinek przed 'jaki'." },
    { id: 36, category: "Interpunkcja", front: "Ten [?] który...", back: "Ten, który...", rule: "Przecinek przed 'który'." },
    { id: 37, category: "Interpunkcja", front: "Człowiek [?] który przyszedł...", back: "Człowiek, który przyszedł,", rule: "Zdanie przydawkowe." },
    { id: 38, category: "Interpunkcja", front: "Książka [?] którą czytam...", back: "Książka, którą czytam,", rule: "Zdanie przydawkowe." },
    { id: 39, category: "Interpunkcja", front: "Dom [?] w którym mieszkam...", back: "Dom, w którym mieszkam,", rule: "Zdanie przydawkowe." },
    { id: 40, category: "Interpunkcja", front: "Dzień [?] kiedy przyjechał...", back: "Dzień, kiedy przyjechał,", rule: "Zdanie przydawkowe." },
    { id: 41, category: "Interpunkcja", front: "Miejsce [?] gdzie się spotkaliśmy...", back: "Miejsce, gdzie się spotkaliśmy,", rule: "Zdanie przydawkowe." },
    { id: 42, category: "Interpunkcja", front: "Powód [?] dla którego...", back: "Powód, dla którego...", rule: "Zdanie przydawkowe." },
    { id: 43, category: "Interpunkcja", front: "Sposób [?] w jaki...", back: "Sposób, w jaki...", rule: "Zdanie przydawkowe." },
    { id: 44, category: "Interpunkcja", front: "Czas [?] gdy...", back: "Czas, gdy...", rule: "Zdanie przydawkowe." },
    { id: 45, category: "Interpunkcja", front: "Moment [?] w którym...", back: "Moment, w którym...", rule: "Zdanie przydawkowe." },
    { id: 46, category: "Interpunkcja", front: "Sytuacja [?] w której...", back: "Sytuacja, w której...", rule: "Zdanie przydawkowe." },
    { id: 47, category: "Interpunkcja", front: "Okoliczności [?] w jakich...", back: "Okoliczności, w jakich...", rule: "Zdanie przydawkowe." },
    { id: 48, category: "Interpunkcja", front: "Warunki [?] w których...", back: "Warunki, w których...", rule: "Zdanie przydawkowe." },
    { id: 49, category: "Interpunkcja", front: "Problem [?] który...", back: "Problem, który...", rule: "Zdanie przydawkowe." },
    { id: 50, category: "Interpunkcja", front: "Kwestia [?] która...", back: "Kwestia, która...", rule: "Zdanie przydawkowe." },
    { id: 51, category: "Interpunkcja", front: "Sprawa [?] o której...", back: "Sprawa, o której...", rule: "Zdanie przydawkowe." },
    { id: 52, category: "Interpunkcja", front: "Temat [?] o którym...", back: "Temat, o którym...", rule: "Zdanie przydawkowe." },
    { id: 53, category: "Interpunkcja", front: "Zagadnienie [?] które...", back: "Zagadnienie, które...", rule: "Zdanie przydawkowe." },
    { id: 54, category: "Interpunkcja", front: "Pomimo [?] że...", back: "Pomimo że...", rule: "Cofanie (jak 'mimo że')." },
    { id: 55, category: "Interpunkcja", front: "Pomimo [?] iż...", back: "Pomimo iż...", rule: "Cofanie przecinka." },
    { id: 56, category: "Interpunkcja", front: "Mimo [?] iż...", back: "Mimo iż...", rule: "Cofanie przecinka." },
    { id: 57, category: "Interpunkcja", front: "Bez względu na to [?] że...", back: "Bez względu na to, że...", rule: "Przecinek przed 'że'." },
    { id: 58, category: "Interpunkcja", front: "Niezależnie od tego [?] że...", back: "Niezależnie od tego, że...", rule: "Przecinek przed 'że'." },
    { id: 59, category: "Interpunkcja", front: "O ile [?] wiem...", back: "O ile wiem,", rule: "Zdanie warunkowe." },
    { id: 60, category: "Interpunkcja", front: "Dopóty [?] dopóki...", back: "Dopóty, dopóki", rule: "Zdanie czasu." },
    { id: 61, category: "Ortografia ó/u", front: "St___ł", back: "Stół", rule: "Ó→O (stół→stołu)." },
    { id: 62, category: "Ortografia ó/u", front: "W___z", back: "Wóz", rule: "Ó→O (wóz→wozu)." },
    { id: 63, category: "Ortografia ó/u", front: "G___ra", back: "Góra", rule: "Ó→O/A (góra→gary)." },
    { id: 64, category: "Ortografia ó/u", front: "Pi___rko", back: "Piórko", rule: "Ó→O (pióro→piórko)." },
    { id: 65, category: "Ortografia ó/u", front: "Dr___żka", back: "Dróżka", rule: "Ó→O (dróżka→droga)." },
    { id: 66, category: "Ortografia ó/u", front: "B___t", back: "But", rule: "U - brak wymiany." },
    { id: 67, category: "Ortografia ó/u", front: "K___bek", back: "Kubek", rule: "U - brak wymiany." },
    { id: 68, category: "Ortografia ó/u", front: "R___ra", back: "Rura", rule: "U - brak wymiany." },
    { id: 69, category: "Ortografia ó/u", front: "Sk___wka", back: "Skuwka", rule: "U - brak wymiany." },
    { id: 70, category: "Ortografia ó/u", front: "Ł___żko", back: "Łóżko", rule: "Ó→O (łóżko→łóżka)." },
    { id: 71, category: "Ortografia ó/u", front: "Dw___r", back: "Dwór", rule: "Ó→O (dwór→dworu)." },
    { id: 72, category: "Ortografia ó/u", front: "Wr___bel", back: "Wróbel", rule: "Ó→O (wróbel→wróble)." },
    { id: 73, category: "Ortografia ó/u", front: "Wr___g", back: "Wróg", rule: "Ó→O (wróg→wroga)." },
    { id: 74, category: "Ortografia ó/u", front: "Kr___l", back: "Król", rule: "Ó→O (król→króla)." },
    { id: 75, category: "Ortografia ó/u", front: "Sł___wik", back: "Słowik", rule: "Ó→O (słowik→słowika)." },
    { id: 76, category: "Ortografia ó/u", front: "Kl___cz", back: "Klucz", rule: "U - brak wymiany." },
    { id: 77, category: "Ortografia ó/u", front: "D___m", back: "Dom", rule: "O - nie ó." },
    { id: 78, category: "Ortografia ó/u", front: "K___ra", back: "Kura", rule: "U - brak wymiany." },
    { id: 79, category: "Ortografia ó/u", front: "M___r", back: "Mur", rule: "U - brak wymiany." },
    { id: 80, category: "Ortografia ó/u", front: "Ł___d", back: "Lód", rule: "Ó→O (lód→lodu)." },
    { id: 81, category: "Ortografia ó/u", front: "R___g", back: "Róg", rule: "Ó→O (róg→rogu)." },
    { id: 82, category: "Ortografia ó/u", front: "B___l", back: "Ból", rule: "Ó→O (ból→bolu)." },
    { id: 83, category: "Ortografia ó/u", front: "Sł___j", back: "Słój", rule: "Ó→O (słój→słoju)." },
    { id: 84, category: "Ortografia ó/u", front: "Ż___łty", back: "Żółty", rule: "Ó→O (żółty→żółta)." },
    { id: 85, category: "Ortografia ó/u", front: "Bi___rko", back: "Biurko", rule: "U - brak wymiany." },
    { id: 86, category: "Ortografia ó/u", front: "Wr___cić", back: "Wrócić", rule: "Ó→A (wrócić→wracać)." },
    { id: 87, category: "Ortografia ó/u", front: "R___żny", back: "Różny", rule: "Ó→O (różny→rozmaity)." },
    { id: 88, category: "Ortografia ó/u", front: "G___rny", back: "Górny", rule: "Ó→O (górny→góra)." },
    { id: 89, category: "Ortografia ó/u", front: "Dł___gi", back: "Długi", rule: "U - brak wymiany." },
    { id: 90, category: "Ortografia ó/u", front: "Kr___tki", back: "Krótki", rule: "Ó→O (krótki→krótka)." },
    { id: 91, category: "Ortografia ó/u", front: "M___wić", back: "Mówić", rule: "Ó→O (mówić→mowa)." },
    { id: 92, category: "Ortografia ó/u", front: "L___bić", back: "Lubić", rule: "U - brak wymiany." },
    { id: 93, category: "Ortografia ó/u", front: "K___t", back: "Kąt", rule: "Ą - nie ó/u." },
    { id: 94, category: "Ortografia ó/u", front: "Cz___rny", back: "Czarny", rule: "A - nie ó/u." },
    { id: 95, category: "Ortografia ó/u", front: "Ziel___ny", back: "Zielony", rule: "O - nie ó/u." },
    { id: 96, category: "Ortografia ó/u", front: "Szer___ki", back: "Szeroki", rule: "O - nie ó/u." },
    { id: 97, category: "Ortografia ó/u", front: "Wys___ki", back: "Wysoki", rule: "O - nie ó/u." },
    { id: 98, category: "Ortografia ó/u", front: "Nisk___", back: "Niski", rule: "I - nie ó/u." },
    { id: 99, category: "Ortografia ó/u", front: "R___bić", back: "Robić", rule: "O - nie ó/u." },
    { id: 100, category: "Ortografia ó/u", front: "Kupi___ć", back: "Kupić", rule: "I - nie ó/u." },
    { id: 101, category: "Ortografia ó/u", front: "Myć", back: "Myć", rule: "Y - nie ó/u." },
    { id: 102, category: "Ortografia ó/u", front: "Prać", back: "Prać", rule: "A - nie ó/u." },
    { id: 103, category: "Ortografia ó/u", front: "Gotow___ć", back: "Gotować", rule: "A - nie ó/u." },
    { id: 104, category: "Ortografia ó/u", front: "Sm___żyć", back: "Smażyć", rule: "A - nie ó/u." },
    { id: 105, category: "Ortografia ó/u", front: "Piec", back: "Piec", rule: "E - nie ó/u." },
    { id: 106, category: "Ortografia ó/u", front: "Gr___ć", back: "Grać", rule: "A - nie ó/u." },
    { id: 107, category: "Ortografia ó/u", front: "Śpiew___ć", back: "Śpiewać", rule: "A - nie ó/u." },
    { id: 108, category: "Ortografia ó/u", front: "Cz___ło", back: "Czoło", rule: "O - nie ó/u." },
    { id: 109, category: "Ortografia ó/u", front: "Dł___ń", back: "Dłoń", rule: "O - nie ó/u." },
    { id: 110, category: "Ortografia ó/u", front: "N___ga", back: "Noga", rule: "O - nie ó/u." },
    { id: 111, category: "Ortografia ó/u", front: "R___ka", back: "Ręka", rule: "Ę - nie ó/u." },
    { id: 112, category: "Ortografia ó/u", front: "Gl___wa", back: "Głowa", rule: "O - nie ó/u." },
    { id: 113, category: "Ortografia ó/u", front: "Ser___e", back: "Serce", rule: "E - nie ó/u." },
    { id: 114, category: "Ortografia ó/u", front: "Pl___cy", back: "Płuca → Płócy", rule: "U - nie ó." },
    { id: 115, category: "Ortografia ó/u", front: "Wątr___ba", back: "Wątroba", rule: "O - nie ó/u." },
    { id: 116, category: "Ortografia ó/u", front: "Żol___dek", back: "Żołądek", rule: "Ą - nie ó/u." },
    { id: 117, category: "Ortografia ó/u", front: "Kr___w", back: "Krew", rule: "E - nie ó/u." },
    { id: 118, category: "Ortografia ó/u", front: "K___ść", back: "Kość", rule: "O - nie ó/u." },
    { id: 119, category: "Ortografia ó/u", front: "Sk___ra", back: "Skóra", rule: "Ó→O (skóra→skóry)." },
    { id: 120, category: "Ortografia ó/u", front: "Wł___sy", back: "Włosy", rule: "O - nie ó/u." },
    { id: 121, category: "Ortografia rz/ż", front: "P___zygoda", back: "Przygoda", rule: "Po P→RZ." },
    { id: 122, category: "Ortografia rz/ż", front: "Dob___ze", back: "Dobrze", rule: "Po B→RZ." },
    { id: 123, category: "Ortografia rz/ż", front: "___zeka", back: "Rzeka", rule: "RZ→R (rzeka→rzeczny)." },
    { id: 124, category: "Ortografia rz/ż", front: "Ksią___ka", back: "Książka", rule: "Ż→G (książka→księgi)." },
    { id: 125, category: "Ortografia rz/ż", front: "In___ynier", back: "Inżynier", rule: "Po N→Ż." },
    { id: 126, category: "Ortografia rz/ż", front: "Ch___zan", back: "Chrzan", rule: "Po CH→RZ." },
    { id: 127, category: "Ortografia rz/ż", front: "Uj___zeć", back: "Ujrzeć", rule: "Po J→RZ." },
    { id: 128, category: "Ortografia rz/ż", front: "Wie___a", back: "Wieża", rule: "Ż→G (wieża→wieżyca)." },
    { id: 129, category: "Ortografia rz/ż", front: "Mo___e", back: "Może", rule: "Ż→G (może→możliwy)." },
    { id: 130, category: "Ortografia rz/ż", front: "G___eszny", back: "Grzeszny", rule: "RZ→R (grzeszny→grzech)." },
    { id: 131, category: "Ortografia rz/ż", front: "Mo___liwy", back: "Możliwy", rule: "Ż→G (możliwy→może)." },
    { id: 132, category: "Ortografia rz/ż", front: "Gro___ny", back: "Groźny", rule: "Ź→Z (groźny→groza)." },
    { id: 133, category: "Ortografia rz/ż", front: "Wie___yca", back: "Wieżyca", rule: "Ż→G." },
    { id: 134, category: "Ortografia rz/ż", front: "P___ebiśnieg", back: "Przebiśnieg", rule: "Po P→RZ." },
    { id: 135, category: "Ortografia rz/ż", front: "T___zeba", back: "Trzeba", rule: "Po T→RZ." },
    { id: 136, category: "Ortografia rz/ż", front: "Ma___z", back: "Marzec", rule: "RZ→R (marzec→marca)." },
    { id: 137, category: "Ortografia rz/ż", front: "Bu___a", back: "Burza", rule: "RZ→R (burza→burzyć)." },
    { id: 138, category: "Ortografia rz/ż", front: "G___zmot", back: "Grzmot", rule: "Po G→RZ." },
    { id: 139, category: "Ortografia rz/ż", front: "K___ak", back: "Krzak", rule: "Po K→RZ." },
    { id: 140, category: "Ortografia rz/ż", front: "K___yk", back: "Krzyk", rule: "Po K→RZ." },
    { id: 141, category: "Ortografia rz/ż", front: "K___esło", back: "Krzesło", rule: "Po K→RZ." },
    { id: 142, category: "Ortografia rz/ż", front: "D___zewo", back: "Drzewo", rule: "Po D→RZ." },
    { id: 143, category: "Ortografia rz/ż", front: "D___wi", back: "Drzwi", rule: "Po D→RZ." },
    { id: 144, category: "Ortografia rz/ż", front: "T___zy", back: "Trzy", rule: "Po T→RZ." },
    { id: 145, category: "Ortografia rz/ż", front: "T___zeci", back: "Trzeci", rule: "Po T→RZ." },
    { id: 146, category: "Ortografia rz/ż", front: "T___zynaście", back: "Trzynaście", rule: "Po T→RZ." },
    { id: 147, category: "Ortografia rz/ż", front: "W___zesień", back: "Wrzesień", rule: "Po W→RZ." },
    { id: 148, category: "Ortografia rz/ż", front: "W___zucić", back: "Wrzucić", rule: "Po W→RZ." },
    { id: 149, category: "Ortografia rz/ż", front: "W___zawa", back: "Wrzawa", rule: "Po W→RZ." },
    { id: 150, category: "Ortografia rz/ż", front: "P___yjaciel", back: "Przyjaciel", rule: "Po P→RZ." },
    { id: 151, category: "Ortografia rz/ż", front: "P___yjemny", back: "Przyjemny", rule: "Po P→RZ." },
    { id: 152, category: "Ortografia rz/ż", front: "P___yjść", back: "Przyjść", rule: "Po P→RZ." },
    { id: 153, category: "Ortografia rz/ż", front: "P___yjąć", back: "Przyjąć", rule: "Po P→RZ." },
    { id: 154, category: "Ortografia rz/ż", front: "P___yjechać", back: "Przyjechać", rule: "Po P→RZ." },
    { id: 155, category: "Ortografia rz/ż", front: "P___yjazd", back: "Przyjazd", rule: "Po P→RZ." },
    { id: 156, category: "Ortografia rz/ż", front: "P___yjemność", back: "Przyjemność", rule: "Po P→RZ." },
    { id: 157, category: "Ortografia rz/ż", front: "P___yjęcie", back: "Przyjęcie", rule: "Po P→RZ." },
    { id: 158, category: "Ortografia rz/ż", front: "P___ypomnieć", back: "Przypomnieć", rule: "Po P→RZ." },
    { id: 159, category: "Ortografia rz/ż", front: "P___ypadek", back: "Przypadek", rule: "Po P→RZ." },
    { id: 160, category: "Ortografia rz/ż", front: "P___ynieść", back: "Przynieść", rule: "Po P→RZ." },
    { id: 161, category: "Ortografia rz/ż", front: "P___yroda", back: "Przyroda", rule: "Po P→RZ." },
    { id: 162, category: "Ortografia rz/ż", front: "P___yszły", back: "Przyszły", rule: "Po P→RZ." },
    { id: 163, category: "Ortografia rz/ż", front: "P___yszłość", back: "Przyszłość", rule: "Po P→RZ." },
    { id: 164, category: "Ortografia rz/ż", front: "P___ygotować", back: "Przygotować", rule: "Po P→RZ." },
    { id: 165, category: "Ortografia rz/ż", front: "P___ykład", back: "Przykład", rule: "Po P→RZ." },
    { id: 166, category: "Ortografia rz/ż", front: "P___yjazny", back: "Przyjazny", rule: "Po P→RZ." },
    { id: 167, category: "Ortografia rz/ż", front: "P___yjemnie", back: "Przyjemnie", rule: "Po P→RZ." },
    { id: 168, category: "Ortografia rz/ż", front: "Ży___afa", back: "Żyrafa", rule: "Ż - wyraz obcy." },
    { id: 169, category: "Ortografia rz/ż", front: "___aba", back: "Żaba", rule: "Ż→G (żaba→żabka)." },
    { id: 170, category: "Ortografia rz/ż", front: "___ycie", back: "Życie", rule: "Ż→G (życie→żyć)." },
    { id: 171, category: "Ortografia rz/ż", front: "___yć", back: "Żyć", rule: "Ż→G." },
    { id: 172, category: "Ortografia rz/ż", front: "___ołnierz", back: "Żołnierz", rule: "Ż→G." },
    { id: 173, category: "Ortografia rz/ż", front: "___ona", back: "Żona", rule: "Ż→G (żona→żonaty)." },
    { id: 174, category: "Ortografia rz/ż", front: "___ółty", back: "Żółty", rule: "Ż→G (żółty→żółtko)." },
    { id: 175, category: "Ortografia rz/ż", front: "___ółw", back: "Żółw", rule: "Ż→G." },
    { id: 176, category: "Ortografia rz/ż", front: "___al", back: "Żal", rule: "Ż→G (żal→żałować)." },
    { id: 177, category: "Ortografia rz/ż", front: "___art", back: "Żart", rule: "Ż→G (żart→żartować)." },
    { id: 178, category: "Ortografia rz/ż", front: "___elazny", back: "Żelazny", rule: "Ż→G (żelazny→żelazo)." },
    { id: 179, category: "Ortografia rz/ż", front: "___elazo", back: "Żelazo", rule: "Ż→G." },
    { id: 180, category: "Ortografia rz/ż", front: "___ołądek", back: "Żołądek", rule: "Ż→G." },
    { id: 181, category: "Ortografia ch/h", front: "Mu___a", back: "Mucha", rule: "CH→SZ (mucha→muszka)." },
    { id: 182, category: "Ortografia ch/h", front: "Su___y", back: "Suchy", rule: "CH→SZ (suchy→susza)." },
    { id: 183, category: "Ortografia ch/h", front: "Bo___ater", back: "Bohater", rule: "H w wyrazach obcych." },
    { id: 184, category: "Ortografia ch/h", front: "___istoria", back: "Historia", rule: "H w wyrazach obcych." },
    { id: 185, category: "Ortografia ch/h", front: "Da___", back: "Dach", rule: "CH na końcu." },
    { id: 186, category: "Ortografia ch/h", front: "Szlo___", back: "Szloch", rule: "CH na końcu." },
    { id: 187, category: "Ortografia ch/h", front: "Gma___", back: "Gmach", rule: "CH na końcu." },
    { id: 188, category: "Ortografia ch/h", front: "S___owek", back: "Schowek", rule: "Po S→CH." },
    { id: 189, category: "Ortografia ch/h", front: "Z___ardzić", back: "Zhardzić", rule: "Po Z→H." },
    { id: 190, category: "Ortografia ch/h", front: "___erbata", back: "Herbata", rule: "H w wyrazach obcych." },
    { id: 191, category: "Ortografia ch/h", front: "___umor", back: "Humor", rule: "H w wyrazach obcych." },
    { id: 192, category: "Ortografia ch/h", front: "___armonijny", back: "Harmonijny", rule: "H w wyrazach obcych." },
    { id: 193, category: "Ortografia ch/h", front: "S___ować", back: "Schować", rule: "Po S→CH." },
    { id: 194, category: "Ortografia ch/h", front: "Wys___nąć", back: "Wyschnąć", rule: "Po S→CH." },
    { id: 195, category: "Ortografia ch/h", front: "___ałas", back: "Hałas", rule: "H w wyrazach obcych." },
    { id: 196, category: "Ortografia ch/h", front: "___ałda", back: "Hałda", rule: "H w wyrazach obcych." },
    { id: 197, category: "Ortografia ch/h", front: "___otel", back: "Hotel", rule: "H w wyrazach obcych." },
    { id: 198, category: "Ortografia ch/h", front: "___isteria", back: "Histeria", rule: "H w wyrazach obcych." },
    { id: 199, category: "Ortografia ch/h", front: "___oryzont", back: "Horyzont", rule: "H w wyrazach obcych." },
    { id: 200, category: "Ortografia ch/h", front: "___ipoteza", back: "Hipoteza", rule: "H w wyrazach obcych." },
    { id: 201, category: "Ortografia ch/h", front: "___ory", back: "Chory", rule: "CH→SZ (chory→choroba)." },
    { id: 202, category: "Ortografia ch/h", front: "___leb", back: "Chleb", rule: "CH - tradycyjna pisownia." },
    { id: 203, category: "Ortografia ch/h", front: "___łopiec", back: "Chłopiec", rule: "CH - tradycyjna pisownia." },
    { id: 204, category: "Ortografia ch/h", front: "___łodny", back: "Chłodny", rule: "CH→SZ (chłodny→chłód)." },
    { id: 205, category: "Ortografia ch/h", front: "___mura", back: "Chmura", rule: "CH - tradycyjna pisownia." },
    { id: 206, category: "Ortografia ch/h", front: "___wila", back: "Chwila", rule: "CH - tradycyjna pisownia." },
    { id: 207, category: "Ortografia ch/h", front: "___wała", back: "Chwała", rule: "CH - tradycyjna pisownia." },
    { id: 208, category: "Ortografia ch/h", front: "___cieć", back: "Chcieć", rule: "CH - tradycyjna pisownia." },
    { id: 209, category: "Ortografia ch/h", front: "___odzić", back: "Chodzić", rule: "CH - tradycyjna pisownia." },
    { id: 210, category: "Ortografia ch/h", front: "___ować", back: "Chować", rule: "CH - tradycyjna pisownia." },
    { id: 211, category: "Ortografia ch/h", front: "U___o", back: "Ucho", rule: "CH - tradycyjna pisownia." },
    { id: 212, category: "Ortografia ch/h", front: "Brzu___", back: "Brzuch", rule: "CH na końcu." },
    { id: 213, category: "Ortografia ch/h", front: "Śmie___", back: "Śmiech", rule: "CH na końcu." },
    { id: 214, category: "Ortografia ch/h", front: "Stra___", back: "Strach", rule: "CH na końcu." },
    { id: 215, category: "Ortografia ch/h", front: "Pa___", back: "Pach", rule: "CH na końcu." },
    { id: 216, category: "Ortografia ch/h", front: "Me___", back: "Mech", rule: "CH na końcu." },
    { id: 217, category: "Ortografia ch/h", front: "___ałaśliwy", back: "Hałaśliwy", rule: "H w wyrazach obcych." },
    { id: 218, category: "Ortografia ch/h", front: "___angar", back: "Hangar", rule: "H w wyrazach obcych." },
    { id: 219, category: "Ortografia ch/h", front: "___ańba", back: "Hańba", rule: "H w wyrazach obcych." },
    { id: 220, category: "Ortografia ch/h", front: "___erbatnik", back: "Herbatnik", rule: "H w wyrazach obcych." },
    { id: 221, category: "Pisownia 'nie'", front: "Nie wiem czy Niewiem", back: "Nie wiem", rule: "Nie+czasownik→osobno." },
    { id: 222, category: "Pisownia 'nie'", front: "Nie rozumiem czy Nierozumiem", back: "Nie rozumiem", rule: "Nie+czasownik→osobno." },
    { id: 223, category: "Pisownia 'nie'", front: "Nie ładny czy Nieładny", back: "Nieładny", rule: "Nie+przymiotnik→łącznie." },
    { id: 224, category: "Pisownia 'nie'", front: "Nie lepszy czy Nielepszy", back: "Nie lepszy", rule: "Nie+stopień wyższy→osobno." },
    { id: 225, category: "Pisownia 'nie'", front: "Nie ład czy Nieład", back: "Nieład", rule: "Nie+rzeczownik→łącznie." },
    { id: 226, category: "Pisownia 'nie'", front: "To ___ie sztuka.", back: "To nie sztuka.", rule: "Nie+orzecznik→osobno." },
    { id: 227, category: "Pisownia 'nie'", front: "Nie mogę czy Niemogę", back: "Nie mogę", rule: "Nie+czasownik→osobno." },
    { id: 228, category: "Pisownia 'nie'", front: "Nie pamiętam czy Niepamiętam", back: "Nie pamiętam", rule: "Nie+czasownik→osobno." },
    { id: 229, category: "Pisownia 'nie'", front: "Nie brzydki czy Niebrzydki", back: "Niebrzydki", rule: "Nie+przymiotnik→łącznie." },
    { id: 230, category: "Pisownia 'nie'", front: "Nie słodki czy Niesłodki", back: "Niesłodki", rule: "Nie+przymiotnik→łącznie." },
    { id: 231, category: "Pisownia 'nie'", front: "Nie potrafię czy Niepotrafię", back: "Nie potrafię", rule: "Nie+czasownik→osobno." },
    { id: 232, category: "Pisownia 'nie'", front: "Nie umiem czy Nieumiem", back: "Nie umiem", rule: "Nie+czasownik→osobno." },
    { id: 233, category: "Pisownia 'nie'", front: "Nie pokój czy Niepokój", back: "Niepokój", rule: "Nie+rzeczownik→łącznie." },
    { id: 234, category: "Pisownia 'nie'", front: "Nie szczęście czy Nieszczęście", back: "Nieszczęście", rule: "Nie+rzeczownik→łącznie." },
    { id: 235, category: "Pisownia 'nie'", front: "Nie wiedza czy Niewiedza", back: "Niewiedza", rule: "Nie+rzeczownik→łącznie." },
    { id: 236, category: "Pisownia 'nie'", front: "Nie chcę czy Niechcę", back: "Nie chcę", rule: "Nie+czasownik→osobno." },
    { id: 237, category: "Pisownia 'nie'", front: "Nie miły czy Niemiły", back: "Niemiły", rule: "Nie+przymiotnik→łącznie." },
    { id: 238, category: "Pisownia 'nie'", front: "Nie najlepszy czy Nienajlepszy", back: "Nie najlepszy", rule: "Nie+stopień najwyższy→osobno." },
    { id: 239, category: "Pisownia 'nie'", front: "Nie dobry czy Niedobry", back: "Niedobry", rule: "Nie+przymiotnik→łącznie." },
    { id: 240, category: "Pisownia 'nie'", front: "Nie zły czy Niezły", back: "Niezły", rule: "Nie+przymiotnik→łącznie." },
    { id: 241, category: "Pisownia 'nie'", front: "Nie prawda czy Nieprawda", back: "Nieprawda", rule: "Nie+rzeczownik→łącznie." },
    { id: 242, category: "Pisownia 'nie'", front: "Nie nawiść czy Nienawiść", back: "Nienawiść", rule: "Nie+rzeczownik→łącznie." },
    { id: 243, category: "Pisownia 'nie'", front: "Nie sprawiedliwość czy Niesprawiedliwość", back: "Niesprawiedliwość", rule: "Nie+rzeczownik→łącznie." },
    { id: 244, category: "Pisownia 'nie'", front: "Nie lubię czy Nielubię", back: "Nie lubię", rule: "Nie+czasownik→osobno." },
    { id: 245, category: "Pisownia 'nie'", front: "Nie mam czy Niemam", back: "Nie mam", rule: "Nie+czasownik→osobno." },
    { id: 246, category: "Pisownia 'nie'", front: "Nie jestem czy Niejestem", back: "Nie jestem", rule: "Nie+czasownik→osobno." },
    { id: 247, category: "Pisownia 'nie'", front: "Nie będę czy Niebędę", back: "Nie będę", rule: "Nie+czasownik→osobno." },
    { id: 248, category: "Pisownia 'nie'", front: "Nie ma czy Niema", back: "Nie ma", rule: "Nie+czasownik→osobno." },
    { id: 249, category: "Pisownia 'nie'", front: "Nie było czy Niebyło", back: "Nie było", rule: "Nie+czasownik→osobno." },
    { id: 250, category: "Pisownia 'nie'", front: "Nie można czy Niemożna", back: "Nie można", rule: "Nie+czasownik→osobno." },
    { id: 251, category: "Pisownia 'nie'", front: "Nie wolno czy Niewolno", back: "Nie wolno", rule: "Nie+czasownik→osobno." },
    { id: 252, category: "Pisownia 'nie'", front: "Nie trzeba czy Nietrzeba", back: "Nie trzeba", rule: "Nie+czasownik→osobno." },
    { id: 253, category: "Pisownia 'nie'", front: "Nie warto czy Niewarto", back: "Nie warto", rule: "Nie+czasownik→osobno." },
    { id: 254, category: "Pisownia 'nie'", front: "Nie należy czy Nienależy", back: "Nie należy", rule: "Nie+czasownik→osobno." },
    { id: 255, category: "Pisownia 'nie'", front: "Nie korzystny czy Niekorzystny", back: "Niekorzystny", rule: "Nie+przymiotnik→łącznie." },
    { id: 256, category: "Pisownia 'nie'", front: "Nie zwykły czy Niezwykły", back: "Niezwykły", rule: "Nie+przymiotnik→łącznie." },
    { id: 257, category: "Pisownia 'nie'", front: "Nie zależny czy Niezależny", back: "Niezależny", rule: "Nie+przymiotnik→łącznie." },
    { id: 258, category: "Pisownia 'nie'", front: "Nie bezpieczny czy Niebezpieczny", back: "Niebezpieczny", rule: "Nie+przymiotnik→łącznie." },
    { id: 259, category: "Pisownia 'nie'", front: "Nie zdrowy czy Niezdrowy", back: "Niezdrowy", rule: "Nie+przymiotnik→łącznie." },
    { id: 260, category: "Pisownia 'nie'", front: "Nie pewny czy Niepewny", back: "Niepewny", rule: "Nie+przymiotnik→łącznie." },
    { id: 261, category: "Rozprawka", front: "Moim zdaniem", back: "Moim zdaniem", rule: "Wyrażenie opinii." },
    { id: 262, category: "Rozprawka", front: "W ogóle", back: "W ogóle", rule: "Pisownia rozdzielna." },
    { id: 263, category: "Rozprawka", front: "Na pewno", back: "Na pewno", rule: "Pisownia rozdzielna." },
    { id: 264, category: "Rozprawka", front: "Konkludując [?]", back: "Konkludując,", rule: "Imiesłów→przecinek." },
    { id: 265, category: "Rozprawka", front: "Należy podkreślić", back: "Należy podkreślić", rule: "Czasownik 'należy'." },
    { id: 266, category: "Rozprawka", front: "Po pierwsze [?]", back: "Po pierwsze,", rule: "Wyliczenie→przecinek." },
    { id: 267, category: "Rozprawka", front: "Po drugie [?]", back: "Po drugie,", rule: "Wyliczenie→przecinek." },
    { id: 268, category: "Rozprawka", front: "Podsumowując [?]", back: "Podsumowując,", rule: "Imiesłów→przecinek." },
    { id: 269, category: "Rozprawka", front: "Z jednej strony [?]", back: "Z jednej strony,", rule: "Wyrażenie→przecinek." },
    { id: 270, category: "Rozprawka", front: "Z drugiej strony [?]", back: "Z drugiej strony,", rule: "Wyrażenie→przecinek." },
    { id: 271, category: "Rozprawka", front: "Niewątpliwie [?]", back: "Niewątpliwie,", rule: "Przysłówek→przecinek." },
    { id: 272, category: "Rozprawka", front: "Bezsprzecznie [?]", back: "Bezsprzecznie,", rule: "Przysłówek→przecinek." },
    { id: 273, category: "Rozprawka", front: "Oczywiście [?]", back: "Oczywiście,", rule: "Przysłówek→przecinek." },
    { id: 274, category: "Rozprawka", front: "Naturalnie [?]", back: "Naturalnie,", rule: "Przysłówek→przecinek." },
    { id: 275, category: "Rozprawka", front: "Zapewne [?]", back: "Zapewne,", rule: "Przysłówek→przecinek." },
    { id: 276, category: "Rozprawka", front: "Prawdopodobnie [?]", back: "Prawdopodobnie,", rule: "Przysłówek→przecinek." },
    { id: 277, category: "Rozprawka", front: "Być może [?]", back: "Być może,", rule: "Wyrażenie→przecinek." },
    { id: 278, category: "Rozprawka", front: "W związku z tym [?]", back: "W związku z tym,", rule: "Wyrażenie→przecinek." },
    { id: 279, category: "Rozprawka", front: "Dlatego też [?]", back: "Dlatego też,", rule: "Wyrażenie→przecinek." },
    { id: 280, category: "Rozprawka", front: "Wobec tego [?]", back: "Wobec tego,", rule: "Wyrażenie→przecinek." },
    { id: 281, category: "Opowiadanie", front: "Ni stąd, ni zowąd", back: "Ni stąd, ni zowąd", rule: "Wyrażenie frazeologiczne." },
    { id: 282, category: "Opowiadanie", front: "Wtem", back: "Wtem", rule: "'Wtem'=nagle." },
    { id: 283, category: "Opowiadanie", front: "Nagle drzwi się otworzyły. [?] drzwi się otworzyły.", back: "Nagle drzwi się otworzyły.", rule: "'Nagle' na początku - bez przecinka." },
    { id: 284, category: "Opowiadanie", front: "Niespodziewanie [?]", back: "Niespodziewanie,", rule: "Przysłówek→przecinek." },
    { id: 285, category: "Opowiadanie", front: "Znienacka [?]", back: "Znienacka,", rule: "Przysłówek→przecinek." },
    { id: 286, category: "Opowiadanie", front: "Raptem [?]", back: "Raptem,", rule: "Przysłówek→przecinek." },
    { id: 287, category: "Opowiadanie", front: "Niechcący", back: "Niechcący", rule: "Przysłówek." },
    { id: 288, category: "Opowiadanie", front: "Nieumyślnie", back: "Nieumyślnie", rule: "Przysłówek." },
    { id: 289, category: "Opowiadanie", front: "Nagłe", back: "Nagłe", rule: "Przymiotnik." },
    { id: 290, category: "Opowiadanie", front: "Wtem", back: "Wtem", rule: "Przysłówek." },
    { id: 291, category: "Wielka litera", front: "uniwersytet / Uniwersytet Warszawski", back: "Uniwersytet Warszawski", rule: "Nazwy własne→wielka." },
    { id: 292, category: "Wielka litera", front: "Wisła", back: "Wisła", rule: "Nazwy geograficzne→wielka." },
    { id: 293, category: "Wielka litera", front: "polska / Polska", back: "Polska", rule: "Nazwy państw→wielka." },
    { id: 294, category: "Wielka litera", front: "warszawa / Warszawa", back: "Warszawa", rule: "Nazwy miast→wielka." },
    { id: 295, category: "Wielka litera", front: "Kraków", back: "Kraków", rule: "Nazwy miast→wielka." },
    { id: 296, category: "Wielka litera", front: "Tatry", back: "Tatry", rule: "Nazwy gór→wielka." },
    { id: 297, category: "Wielka litera", front: "Bałtyk", back: "Bałtyk", rule: "Nazwy mórz→wielka." },
    { id: 298, category: "Wielka litera", front: "Europa", back: "Europa", rule: "Nazwy kontynentów→wielka." },
    { id: 299, category: "Wielka litera", front: "Ziemia (planeta)", back: "Ziemia", rule: "Nazwy planet→wielka." },
    { id: 300, category: "Wielka litera", front: "Poznań", back: "Poznań", rule: "Nazwy miast→wielka." },
    { id: 301, category: "Ortografia rz/ż", front: "D___ewo", back: "Drzewo", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 302, category: "Ortografia rz/ż", front: "K___ak", back: "Krzak", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 303, category: "Ortografia rz/ż", front: "B___oza", back: "Brzoza", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 304, category: "Ortografia rz/ż", front: "T___askać", back: "Trzaskać", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 305, category: "Ortografia rz/ż", front: "G___ebać", back: "Grzebać", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 306, category: "Ortografia rz/ż", front: "Ch___ąstka", back: "Chrząstka", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 307, category: "Ortografia rz/ż", front: "Zaj___eć", back: "Zajrzeć", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 308, category: "Ortografia rz/ż", front: "W___osowisko", back: "Wrzosowisko", rule: "RZ piszemy po spółgłoskach: b, p, d, t, g, k, ch, j, w." },
    { id: 309, category: "Ortografia rz/ż", front: "Mala___", back: "Malarz", rule: "RZ piszemy w zakończeniach wyrazów: -arz." },
    { id: 310, category: "Ortografia rz/ż", front: "Kołnie___", back: "Kołnierz", rule: "RZ piszemy w zakończeniach wyrazów: -erz." },
    { id: 311, category: "Ortografia rz/ż", front: "Kazimie___", back: "Kazimierz", rule: "RZ piszemy w zakończeniach wyrazów: -mierz." },
    { id: 312, category: "Ortografia rz/ż", front: "Sztukmi___trz", back: "Sztukmistrz", rule: "RZ piszemy w zakończeniach wyrazów: -mistrz." },
    { id: 313, category: "Ortografia rz/ż", front: "T___rca", back: "Twórca", rule: "RZ piszemy, gdy wymienia się na R (tworzyć)." },
    { id: 314, category: "Ortografia rz/ż", front: "Mo___e", back: "Morze", rule: "RZ piszemy, gdy wymienia się na R (morski),." },
    { id: 315, category: "Ortografia rz/ż", front: "Pszczo___a", back: "Pszczoła", rule: "Wyjątek: RZ po P (mimo zasady piszemy PSZ)." },
    { id: 316, category: "Ortografia rz/ż", front: "Kszta___t", back: "Kształt", rule: "Wyjątek: SZ po K (mimo zasady piszemy KSZ)." },
    { id: 317, category: "Ortografia rz/ż", front: "Lep___y", back: "Lepszy", rule: "Wyjątek w przymiotnikach zakończonych na -szy." },
    { id: 318, category: "Ortografia rz/ż", front: "Mosię___ny", back: "Mosiężny", rule: "Ż piszemy, gdy wymienia się na dz (mosiądz)." },
    { id: 319, category: "Ortografia rz/ż", front: "Wska___ę", back: "Wskażę", rule: "Ż piszemy, gdy wymienia się na z (wskazać)." },
    { id: 320, category: "Ortografia rz/ż", front: "Dru___yna", back: "Drużyna", rule: "Ż piszemy, gdy wymienia się na h (druh)." },
    { id: 321, category: "Ortografia rz/ż", front: "Gara___", back: "Garaż", rule: "Ż piszemy w wyrazach zakończonych na -aż." },
    { id: 322, category: "Ortografia rz/ż", front: "Młodzie___", back: "Młodzież", rule: "Ż piszemy w wyrazach zakończonych na -ież/-eż." },
    { id: 323, category: "Ortografia rz/ż", front: "L___ej", back: "Lżej", rule: "Ż piszemy po literze l." },
    { id: 324, category: "Ortografia rz/ż", front: "Mał___onka", back: "Małżonka", rule: "Ż piszemy po literze ł." },
    { id: 325, category: "Ortografia rz/ż", front: "Rewan___", back: "Rewanż", rule: "Ż piszemy po literze n." },
    { id: 326, category: "Ortografia ó/u", front: "Wz___r", back: "Wzór", rule: "Ó piszemy, gdy wymienia się na o/e/a (wzory),." },
    { id: 327, category: "Ortografia ó/u", front: "Zapas___w", back: "Zapasów", rule: "Ó piszemy w zakończeniach -ów,." },
    { id: 328, category: "Ortografia ó/u", front: "Sk___wka", back: "Skuwka", rule: "Wyjątek: piszemy U, mimo zakończenia fonetycznego,." },
    { id: 329, category: "Ortografia ó/u", front: "Zas___wka", back: "Zasuwka", rule: "Wyjątek: piszemy U, mimo zakończenia fonetycznego." },
    { id: 330, category: "Ortografia ó/u", front: "Ws___wka", back: "Wsuwka", rule: "Wyjątek: piszemy U, mimo zakończenia fonetycznego." },
    { id: 331, category: "Ortografia ó/u", front: "___stawa", back: "Ustawa", rule: "U piszemy na początku wyrazu." },
    { id: 332, category: "Ortografia ó/u", front: "___smy", back: "Ósmy", rule: "Wyjątek: Ó na początku wyrazu,." },
    { id: 333, category: "Ortografia ó/u", front: "___wczesny", back: "Ówczesny", rule: "Wyjątek: Ó na początku wyrazu." },
    { id: 334, category: "Ortografia ó/u", front: "Cieni___tki", back: "Cieniutki", rule: "U piszemy w zakończeniach typu -utki." },
    { id: 335, category: "Ortografia ó/u", front: "Mal___śki", back: "Maluśki", rule: "U piszemy w zakończeniach typu -uś/-uśki." },
    { id: 336, category: "Ortografia ó/u", front: "B___l", back: "Ból", rule: "Ó wymienne (boli)." },
    { id: 337, category: "Ortografia ó/u", front: "M___j", back: "Mój", rule: "Ó wymienia się na o (moje)." },
    { id: 338, category: "Ortografia ó/u", front: "Dw___r", back: "Dwór", rule: "Ó wymienia się na o (dwory)." },
    { id: 339, category: "Ortografia ó/u", front: "Przywi___dł", back: "Przywiódł", rule: "Ó wymienia się na o (przywiodła)." },
    { id: 340, category: "Ortografia ó/u", front: "C___rka", back: "Córka", rule: "Ó niewymienne (należy zapamiętać)." },
    { id: 341, category: "Ortografia ó/u", front: "R___ża", back: "Róża", rule: "Ó niewymienne." },
    { id: 342, category: "Ortografia ó/u", front: "Pr___żne", back: "Próżne", rule: "Ó niewymienne." },
    { id: 343, category: "Ortografia ó/u", front: "P___źniej", back: "Później", rule: "Ó niewymienne." },
    { id: 344, category: "Ortografia ó/u", front: "Dw___ch", back: "Dwóch", rule: "Ó wymienne (dwoje)." },
    { id: 345, category: "Ortografia ó/u", front: "Spos___b", back: "Sposób", rule: "Ó wymienne (sposoby)." },
    { id: 346, category: "Ortografia ch/h", front: "Dru___", back: "Druh", rule: "Wyjątek: H na końcu wyrazu." },
    { id: 347, category: "Ortografia ch/h", front: "Ci___o", back: "Cicho", rule: "CH piszemy, gdy wymienia się na sz (cisza)." },
    { id: 348, category: "Ortografia ch/h", front: "S___arakteryzować", back: "Scharakteryzować", rule: "CH piszemy po literze s." },
    { id: 349, category: "Ortografia ch/h", front: "Pu___", back: "Puch", rule: "CH piszemy na końcu wyrazu." },
    { id: 350, category: "Ortografia ch/h", front: "Dru___na", back: "Druhna", rule: "H piszemy, gdy wymienia się na ż (drużyna)." },
    { id: 351, category: "Ortografia ch/h", front: "Z___armonizować", back: "Zharmonizować", rule: "H piszemy po literze z." },
    { id: 352, category: "Ortografia ch/h", front: "C___rypa", back: "Chrypa", rule: "CH niewymienne (dyktando)." },
    { id: 353, category: "Ortografia ch/h", front: "Wa___ać się", back: "Wahać się", rule: "H niewymienne (dyktando)." },
    { id: 354, category: "Ortografia ch/h", front: "Bo___ater", back: "Bohater", rule: "H niewymienne (dyktando)." },
    { id: 355, category: "Ortografia ch/h", front: "Pe___ch", back: "Pech", rule: "CH na końcu wyrazu." },
    { id: 356, category: "Pisownia 'nie'", front: "(Nie)chęć", back: "Niechęć", rule: "Nie z rzeczownikami piszemy łącznie." },
    { id: 357, category: "Pisownia 'nie'", front: "(Nie)porządek", back: "Nieporządek", rule: "Nie z rzeczownikami piszemy łącznie." },
    { id: 358, category: "Pisownia 'nie'", front: "(Nie)lubię", back: "Nie lubię", rule: "Nie z czasownikami piszemy oddzielnie." },
    { id: 359, category: "Pisownia 'nie'", front: "(Nie)ma", back: "Nie ma", rule: "Nie z czasownikami piszemy oddzielnie." },
    { id: 360, category: "Pisownia 'nie'", front: "(Nie)dostrzegać", back: "Nie dostrzegać", rule: "Nie z bezokolicznikami piszemy oddzielnie." },
    { id: 361, category: "Pisownia 'nie'", front: "(Nie)pokoić", back: "Niepokoić", rule: "Wyjątek: czasownik pisany łącznie." },
    { id: 362, category: "Pisownia 'nie'", front: "(Nie)nawidzić", back: "Nienawidzić", rule: "Wyjątek: czasownik pisany łącznie." },
    { id: 363, category: "Pisownia 'nie'", front: "(Nie)można", back: "Nie można", rule: "Wyrazy o znaczeniu czasownikowym piszemy oddzielnie." },
    { id: 364, category: "Pisownia 'nie'", front: "(Nie)warto", back: "Nie warto", rule: "Wyrazy o znaczeniu czasownikowym piszemy oddzielnie." },
    { id: 365, category: "Pisownia 'nie'", front: "(Nie)ładny", back: "Nieładny", rule: "Nie z przymiotnikami w stopniu równym piszemy łącznie." },
    { id: 366, category: "Pisownia 'nie'", front: "(Nie)większy", back: "Nie większy", rule: "Nie z przymiotnikami w stopniu wyższym piszemy oddzielnie." },
    { id: 367, category: "Pisownia 'nie'", front: "(Nie)najlepszy", back: "Nie najlepszy", rule: "Nie z przymiotnikami w stopniu najwyższym piszemy oddzielnie." },
    { id: 368, category: "Pisownia 'nie'", front: "(Nie)chętnie", back: "Niechętnie", rule: "Nie z przysłówkami odprzymiotnikowymi w st. równym łącznie." },
    { id: 369, category: "Pisownia 'nie'", front: "(Nie)bardzo", back: "Nie bardzo", rule: "Nie z przysłówkami nieodprzymiotnikowymi oddzielnie." },
    { id: 370, category: "Pisownia 'nie'", front: "(Nie)dziś", back: "Nie dziś", rule: "Nie z przysłówkami nieodprzymiotnikowymi oddzielnie." },
    { id: 371, category: "Pisownia 'nie'", front: "(Nie)palący", back: "Niepalący", rule: "Nie z imiesłowami przymiotnikowymi łącznie." },
    { id: 372, category: "Pisownia 'nie'", front: "(Nie)czekając", back: "Nie czekając", rule: "Nie z imiesłowami przysłówkowymi oddzielnie." },
    { id: 373, category: "Pisownia 'nie'", front: "(Nie)trzy", back: "Nie trzy", rule: "Nie z liczebnikami oddzielnie." },
    { id: 374, category: "Pisownia 'nie'", front: "(Nie)jeden", back: "Niejeden", rule: "Wyjątek liczebnikowy (w znaczeniu wielu) łącznie." },
    { id: 375, category: "Pisownia 'nie'", front: "(Nie)ja", back: "Nie ja", rule: "Nie z zaimkami oddzielnie." },
    { id: 376, category: "Wielka litera", front: "___dam ___ickiewicz", back: "Adam Mickiewicz", rule: "Imiona i nazwiska piszemy wielką literą." },
    { id: 377, category: "Wielka litera", front: "___olesław ___hrobry", back: "Bolesław Chrobry", rule: "Przydomki piszemy wielką literą." },
    { id: 378, category: "Wielka litera", front: "___oże ___arodzenie", back: "Boże Narodzenie", rule: "Nazwy świąt piszemy wielką literą." },
    { id: 379, category: "Wielka litera", front: "___owisz", back: "Jowisz", rule: "Nazwy planet piszemy wielką literą." },
    { id: 380, category: "Wielka litera", front: "___meryka", back: "Ameryka", rule: "Nazwy kontynentów piszemy wielką literą." },
    { id: 381, category: "Wielka litera", front: "___olak", back: "Polak", rule: "Nazwy mieszkańców państw piszemy wielką literą." },
    { id: 382, category: "Wielka litera", front: "___omorzanin", back: "Pomorzanin", rule: "Nazwy mieszkańców regionów piszemy wielką literą." },
    { id: 383, category: "Wielka litera", front: "___ahara", back: "Sahara", rule: "Nazwy geograficzne piszemy wielką literą." },
    { id: 384, category: "Wielka litera", front: "___arab", back: "Arab", rule: "Nazwy przedstawicieli ras/nacji piszemy wielką literą." },
    { id: 385, category: "Wielka litera", front: "___awel", back: "Wawel", rule: "Nazwy budowli i zabytków piszemy wielką literą." },
    { id: 386, category: "Mała litera", front: "___olski (przymiotnik)", back: "polski", rule: "Przymiotniki od nazw krajów piszemy małą literą." },
    { id: 387, category: "Mała litera", front: "___arszawiak", back: "warszawiak", rule: "Nazwy mieszkańców miast piszemy małą literą." },
    { id: 388, category: "Mała litera", front: "___rudzień", back: "grudzień", rule: "Nazwy miesięcy piszemy małą literą." },
    { id: 389, category: "Wielka litera", front: "___ejm ___zeczypospolitej ___olskiej", back: "Sejm Rzeczypospolitej Polskiej", rule: "Nazwy urzędów i instytucji piszemy wielką literą." },
    { id: 390, category: "Wielka litera", front: "___nica ___uławska", back: "Ulica Puławska", rule: "Nazwy ulic piszemy wielką literą (wg źródła)." },
    { id: 391, category: "Interpunkcja", front: "Zdanie: Kiedy wrócę ___ zjem obiad.", back: "Kiedy wrócę, zjem obiad.", rule: "Zdanie podrzędne oddzielamy przecinkiem." },
    { id: 392, category: "Interpunkcja", front: "Zdanie: Idąc do szkoły ___ kupił gazetę.", back: "Idąc do szkoły, kupił gazetę.", rule: "Imiesłów przysłówkowy oddzielamy przecinkiem." },
    { id: 393, category: "Interpunkcja", front: "Zdanie: Myślę ___ więc jestem.", back: "Myślę, więc jestem.", rule: "Przed spójnikiem 'więc' stawiamy przecinek." },
    { id: 394, category: "Interpunkcja", front: "Zdanie: Mimo ___ że padało.", back: "Mimo że padało.", rule: "Nie rozdzielamy przecinkiem połączenia 'mimo że',." },
    { id: 395, category: "Interpunkcja", front: "Zdanie: Lubię kawę ___ ale nie herbatę.", back: "Lubię kawę, ale nie herbaty.", rule: "Przed spójnikiem 'ale' stawiamy przecinek." },
    { id: 396, category: "Interpunkcja", front: "Zdanie: Chcę ___ abyś przyszedł.", back: "Chcę, abyś przyszedł.", rule: "Przed spójnikiem 'aby' stawiamy przecinek." },
    { id: 397, category: "Interpunkcja", front: "Zdanie: Lubię lody ___ albo gofry.", back: "Lubię lody albo gofry.", rule: "Nie stawiamy przecinka przed 'albo' (współrzędność)." },
    { id: 398, category: "Poprawność językowa", front: "Forma: Wziąć czy Wziąść?", back: "Wziąć", rule: "Poprawna forma to wziąć." },
    { id: 399, category: "Poprawność językowa", front: "Forma: W dniu dzisiejszym czy Dzisiaj?", back: "Dzisiaj", rule: "Unikamy formy 'w dniu dzisiejszym'." },
    { id: 400, category: "Poprawność językowa", front: "Forma: Przekonywujący czy Przekonujący?", back: "Przekonujący", rule: "Poprawna forma to przekonujący." }
];

if (typeof module !== 'undefined') {
    module.exports = flashcards;
}
