const flashcards = [
    // === INTERPUNKCJA (60 cards) ===
    { id: 1, category: "Interpunkcja", front: "Warto zauważyć [?] że...", back: "Warto zauważyć, że...", rule: "Przed 'że' wprowadzającym zdanie podrzędne zawsze stawiamy przecinek." },
    { id: 2, category: "Interpunkcja", front: "Mimo [?] że padało, poszliśmy.", back: "Mimo że padało, poszliśmy.", rule: "W 'mimo że' przecinek stawiamy PRZED całym wyrażeniem (cofanie przecinka)." },
    { id: 3, category: "Interpunkcja", front: "Nie poszedłem [?] ponieważ byłem chory.", back: "Nie poszedłem, ponieważ byłem chory.", rule: "Przed 'ponieważ' zawsze stawiamy przecinek." },
    { id: 4, category: "Interpunkcja", front: "Przyjdę [?] chyba że będzie padać.", back: "Przyjdę, chyba że będzie padać.", rule: "Przed 'chyba że' stawiamy przecinek (cofanie)." },
    { id: 5, category: "Interpunkcja", front: "Zrobię to [?] tylko że nie dzisiaj.", back: "Zrobię to, tylko że nie dzisiaj.", rule: "Przed 'tylko że' stawiamy przecinek." },
    { id: 6, category: "Interpunkcja", front: "Powiedział [?] że przyjdzie.", back: "Powiedział, że przyjdzie.", rule: "Przecinek przed 'że' w zdaniu podrzędnym." },
    { id: 7, category: "Interpunkcja", front: "Myślę [?] że to dobry pomysł.", back: "Myślę, że to dobry pomysł.", rule: "Przecinek przed 'że'." },
    { id: 8, category: "Interpunkcja", front: "Wiem [?] że masz rację.", back: "Wiem, że masz rację.", rule: "Przecinek przed 'że'." },
    { id: 9, category: "Interpunkcja", front: "Cieszę się [?] że przyszedłeś.", back: "Cieszę się, że przyszedłeś.", rule: "Przecinek przed 'że'." },
    { id: 10, category: "Interpunkcja", front: "Podczas [?] gdy on spał, ja pracowałem.", back: "Podczas gdy on spał, ja pracowałem.", rule: "Cofanie przecinka przed 'podczas gdy'." },
    { id: 11, category: "Interpunkcja", front: "Chociaż [?] był zmęczony, poszedł.", back: "Chociaż był zmęczony, poszedł.", rule: "Zdanie podrzędne na początku - przecinek po nim." },
    { id: 12, category: "Interpunkcja", front: "Jeśli [?] przyjdziesz, będę szczęśliwy.", back: "Jeśli przyjdziesz, będę szczęśliwy.", rule: "Zdanie warunkowe na początku." },
    { id: 13, category: "Interpunkcja", front: "Kiedy [?] wrócisz, zadzwoń.", back: "Kiedy wrócisz, zadzwoń.", rule: "Zdanie podrzędne czasu na początku." },
    { id: 14, category: "Interpunkcja", front: "Ponieważ [?] padało, zostałem w domu.", back: "Ponieważ padało, zostałem w domu.", rule: "Zdanie przyczynowe na początku." },
    { id: 15, category: "Interpunkcja", front: "Gdyby [?] wiedział, powiedziałby.", back: "Gdyby wiedział, powiedziałby.", rule: "Zdanie warunkowe." },
    { id: 16, category: "Interpunkcja", front: "Dlatego [?] że...", back: "Dlatego że...", rule: "Cofanie przecinka - przed całym wyrażeniem 'dlatego że'." },
    { id: 17, category: "Interpunkcja", front: "Jako [?] że...", back: "Jako że...", rule: "Cofanie przecinka." },
    { id: 18, category: "Interpunkcja", front: "Tym bardziej [?] że...", back: "Tym bardziej że...", rule: "Cofanie przecinka." },
    { id: 19, category: "Interpunkcja", front: "Aczkolwiek [?]", back: "Aczkolwiek,", rule: "Spójnik - przecinek." },
    { id: 20, category: "Interpunkcja", front: "Jednakże [?]", back: "Jednakże,", rule: "Spójnik - przecinek." },
    { id: 21, category: "Interpunkcja", front: "Jeżeli [?] przyjdziesz...", back: "Jeżeli przyjdziesz,", rule: "Zdanie warunkowe." },
    { id: 22, category: "Interpunkcja", front: "Gdyby [?] mógł...", back: "Gdyby mógł,", rule: "Zdanie warunkowe." },
    { id: 23, category: "Interpunkcja", front: "Zanim [?] wyjdziesz...", back: "Zanim wyjdziesz,", rule: "Zdanie podrzędne czasu." },
    { id: 24, category: "Interpunkcja", front: "Dopóki [?] nie wrócisz...", back: "Dopóki nie wrócisz,", rule: "Zdanie podrzędne czasu." },
    { id: 25, category: "Interpunkcja", front: "Odkąd [?] wyjechał...", back: "Odkąd wyjechał,", rule: "Zdanie podrzędne czasu." },
    { id: 26, category: "Interpunkcja", front: "Skoro [?] tak mówisz...", back: "Skoro tak mówisz,", rule: "Zdanie podrzędne przyczynowe." },
    { id: 27, category: "Interpunkcja", front: "Ponieważ [?] jest zimno...", back: "Ponieważ jest zimno,", rule: "Zdanie przyczynowe." },
    { id: 28, category: "Interpunkcja", front: "Choć [?] był chory...", back: "Choć był chory,", rule: "Zdanie przyzwolenia." },
    { id: 29, category: "Interpunkcja", front: "Choćby [?] chciał...", back: "Choćby chciał,", rule: "Zdanie przyzwolenia." },
    { id: 30, category: "Interpunkcja", front: "Ażeby [?] było lepiej...", back: "Ażeby było lepiej,", rule: "Zdanie celowe." },
    { id: 31, category: "Interpunkcja", front: "Żeby [?] było jasne...", back: "Żeby było jasne,", rule: "Zdanie celowe." },
    { id: 32, category: "Interpunkcja", front: "Aby [?] zrozumieć...", back: "Aby zrozumieć,", rule: "Zdanie celowe." },
    { id: 33, category: "Interpunkcja", front: "Tak [?] że...", back: "Tak, że...", rule: "Przecinek przed 'że'." },
    { id: 34, category: "Interpunkcja", front: "Taki [?] że...", back: "Taki, że...", rule: "Przecinek przed 'że'." },
    { id: 35, category: "Interpunkcja", front: "Wtedy [?] gdy...", back: "Wtedy, gdy...", rule: "Przecinek przed 'gdy'." },
    { id: 36, category: "Interpunkcja", front: "Tam [?] gdzie...", back: "Tam, gdzie...", rule: "Przecinek przed 'gdzie'." },
    { id: 37, category: "Interpunkcja", front: "Taki [?] jaki...", back: "Taki, jaki...", rule: "Przecinek przed 'jaki'." },
    { id: 38, category: "Interpunkcja", front: "Ten [?] który...", back: "Ten, który...", rule: "Przecinek przed 'który'." },
    { id: 39, category: "Interpunkcja", front: "Człowiek [?] który przyszedł...", back: "Człowiek, który przyszedł,", rule: "Zdanie przydawkowe - przecinki z obu stron." },
    { id: 40, category: "Interpunkcja", front: "Książka [?] którą czytam...", back: "Książka, którą czytam,", rule: "Zdanie przydawkowe." },
    { id: 41, category: "Interpunkcja", front: "Dom [?] w którym mieszkam...", back: "Dom, w którym mieszkam,", rule: "Zdanie przydawkowe." },
    { id: 42, category: "Interpunkcja", front: "Dzień [?] kiedy przyjechał...", back: "Dzień, kiedy przyjechał,", rule: "Zdanie przydawkowe." },
    { id: 43, category: "Interpunkcja", front: "Miejsce [?] gdzie się spotkaliśmy...", back: "Miejsce, gdzie się spotkaliśmy,", rule: "Zdanie przydawkowe." },
    { id: 44, category: "Interpunkcja", front: "Powód [?] dla którego...", back: "Powód, dla którego...", rule: "Zdanie przydawkowe." },
    { id: 45, category: "Interpunkcja", front: "Sposób [?] w jaki...", back: "Sposób, w jaki...", rule: "Zdanie przydawkowe." },
    { id: 46, category: "Interpunkcja", front: "Czas [?] gdy...", back: "Czas, gdy...", rule: "Zdanie przydawkowe." },
    { id: 47, category: "Interpunkcja", front: "Moment [?] w którym...", back: "Moment, w którym...", rule: "Zdanie przydawkowe." },
    { id: 48, category: "Interpunkcja", front: "Sytuacja [?] w której...", back: "Sytuacja, w której...", rule: "Zdanie przydawkowe." },
    { id: 49, category: "Interpunkcja", front: "Okoliczności [?] w jakich...", back: "Okoliczności, w jakich...", rule: "Zdanie przydawkowe." },
    { id: 50, category: "Interpunkcja", front: "Warunki [?] w których...", back: "Warunki, w których...", rule: "Zdanie przydawkowe." },
    { id: 51, category: "Interpunkcja", front: "Problem [?] który...", back: "Problem, który...", rule: "Zdanie przydawkowe." },
    { id: 52, category: "Interpunkcja", front: "Kwestia [?] która...", back: "Kwestia, która...", rule: "Zdanie przydawkowe." },
    { id: 53, category: "Interpunkcja", front: "Sprawa [?] o której...", back: "Sprawa, o której...", rule: "Zdanie przydawkowe." },
    { id: 54, category: "Interpunkcja", front: "Temat [?] o którym...", back: "Temat, o którym...", rule: "Zdanie przydawkowe." },
    { id: 55, category: "Interpunkcja", front: "Zagadnienie [?] które...", back: "Zagadnienie, które...", rule: "Zdanie przydawkowe." },
    { id: 56, category: "Interpunkcja", front: "Pomimo [?] że...", back: "Pomimo że...", rule: "Cofanie przecinka (jak 'mimo że')." },
    { id: 57, category: "Interpunkcja", front: "Pomimo [?] iż...", back: "Pomimo iż...", rule: "Cofanie przecinka." },
    { id: 58, category: "Interpunkcja", front: "Mimo [?] iż...", back: "Mimo iż...", rule: "Cofanie przecinka." },
    { id: 59, category: "Interpunkcja", front: "Bez względu na to [?] że...", back: "Bez względu na to, że...", rule: "Przecinek przed 'że'." },
    { id: 60, category: "Interpunkcja", front: "Niezależnie od tego [?] że...", back: "Niezależnie od tego, że...", rule: "Przecinek przed 'że'." },

    // === ORTOGRAFIA ó/u (60 cards) ===
    { id: 61, category: "Ortografia ó/u", front: "St_ł", back: "Stół", rule: "Ó wymienia się na O (stół → stołu)." },
    { id: 62, category: "Ortografia ó/u", front: "W_z", back: "Wóz", rule: "Ó wymienia się na O (wóz → wozu)." },
    { id: 63, category: "Ortografia ó/u", front: "G_ra", back: "Góra", rule: "Ó wymienia się na O/A (góra → gary)." },
    { id: 64, category: "Ortografia ó/u", front: "Pi_rko", back: "Piórko", rule: "Ó wymienia się na O (pióro → piórko)." },
    { id: 65, category: "Ortografia ó/u", front: "Dr_żka", back: "Dróżka", rule: "Ó wymienia się na O (dróżka → droga)." },
    { id: 66, category: "Ortografia ó/u", front: "B_t", back: "But", rule: "U - brak wymiany (but → buta)." },
    { id: 67, category: "Ortografia ó/u", front: "K_bek", back: "Kubek", rule: "U - brak wymiany." },
    { id: 68, category: "Ortografia ó/u", front: "R_ra", back: "Rura", rule: "U - brak wymiany." },
    { id: 69, category: "Ortografia ó/u", front: "Sk_wka", back: "Skuwka", rule: "U - brak wymiany." },
    { id: 70, category: "Ortografia ó/u", front: "Ł_żko", back: "Łóżko", rule: "Ó wymienia się na O (łóżko → łóżka)." },
    { id: 71, category: "Ortografia ó/u", front: "Dw_r", back: "Dwór", rule: "Ó wymienia się na O (dwór → dworu)." },
    { id: 72, category: "Ortografia ó/u", front: "Wr_bel", back: "Wróbel", rule: "Ó wymienia się na O (wróbel → wróble)." },
    { id: 73, category: "Ortografia ó/u", front: "Wr_g", back: "Wróg", rule: "Ó wymienia się na O (wróg → wroga)." },
    { id: 74, category: "Ortografia ó/u", front: "Kr_l", back: "Król", rule: "Ó wymienia się na O (król → króla)." },
    { id: 75, category: "Ortografia ó/u", front: "Sł_wik", back: "Słowik", rule: "Ó wymienia się na O (słowik → słowika)." },
    { id: 76, category: "Ortografia ó/u", front: "Kl_cz", back: "Klucz", rule: "U - brak wymiany." },
    { id: 77, category: "Ortografia ó/u", front: "D_m", back: "Dom", rule: "O - nie ó (dom → domu)." },
    { id: 78, category: "Ortografia ó/u", front: "K_ra", back: "Kura", rule: "U - brak wymiany." },
    { id: 79, category: "Ortografia ó/u", front: "M_r", back: "Mur", rule: "U - brak wymiany." },
    { id: 80, category: "Ortografia ó/u", front: "S_r", back: "Sór → Ser", rule: "O/E - nie ó ani u." },
    { id: 81, category: "Ortografia ó/u", front: "Ł_d", back: "Lód", rule: "Ó wymienia się na O (lód → lodu)." },
    { id: 82, category: "Ortografia ó/u", front: "R_g", back: "Róg", rule: "Ó wymienia się na O (róg → rogu)." },
    { id: 83, category: "Ortografia ó/u", front: "B_l", back: "Ból", rule: "Ó wymienia się na O (ból → bolu)." },
    { id: 84, category: "Ortografia ó/u", front: "Sł_j", back: "Słój", rule: "Ó wymienia się na O (słój → słoju)." },
    { id: 85, category: "Ortografia ó/u", front: "Zł_ty", back: "Złoty", rule: "O - nie ó (złoto)." },
    { id: 86, category: "Ortografia ó/u", front: "Ż_łty", back: "Żółty", rule: "Ó wymienia się na O (żółty → żółta)." },
    { id: 87, category: "Ortografia ó/u", front: "Ziel_ny", back: "Zielony", rule: "O - nie ó ani u." },
    { id: 88, category: "Ortografia ó/u", front: "Cz_rny", back: "Czarny → Czórny", rule: "A - nie ó ani u." },
    { id: 89, category: "Ortografia ó/u", front: "Bi_rko", back: "Biurko", rule: "U - brak wymiany." },
    { id: 90, category: "Ortografia ó/u", front: "K_t", back: "Kąt → Kót", rule: "Ą - nie ó ani u." },
    { id: 91, category: "Ortografia ó/u", front: "Wr_cić", back: "Wrócić", rule: "Ó wymienia się na A (wrócić → wracać)." },
    { id: 92, category: "Ortografia ó/u", front: "R_żny", back: "Różny", rule: "Ó wymienia się na O (różny → rozmaity)." },
    { id: 93, category: "Ortografia ó/u", front: "G_rny", back: "Górny", rule: "Ó wymienia się na O (górny → góra)." },
    { id: 94, category: "Ortografia ó/u", front: "Dł_gi", back: "Długi", rule: "U - brak wymiany." },
    { id: 95, category: "Ortografia ó/u", front: "Kr_tki", back: "Krótki", rule: "Ó wymienia się na O (krótki → krótka)." },
    { id: 96, category: "Ortografia ó/u", front: "Wąski / w_ski", back: "Wąski", rule: "Ą - nie ó ani u." },
    { id: 97, category: "Ortografia ó/u", front: "Szer_ki", back: "Szeroki", rule: "O - nie ó ani u." },
    { id: 98, category: "Ortografia ó/u", front: "Wys_ki", back: "Wysoki", rule: "O - nie ó ani u." },
    { id: 99, category: "Ortografia ó/u", front: "Nisk_", back: "Niski → Nisko", rule: "O - nie ó ani u." },
    { id: 100, category: "Ortografia ó/u", front: "G_sty", back: "Gęsty → Gósty", rule: "Ę - nie ó ani u." },
    { id: 101, category: "Ortografia ó/u", front: "Rzadk_", back: "Rzadki → Rzódki", rule: "A - nie ó ani u." },
    { id: 102, category: "Ortografia ó/u", front: "Cięzk_ / Ci_żki", back: "Ciężki", rule: "Ę - nie ó ani u." },
    { id: 103, category: "Ortografia ó/u", front: "L_bić", back: "Lubić", rule: "U - brak wymiany." },
    { id: 104, category: "Ortografia ó/u", front: "M_wić", back: "Mówić", rule: "Ó wymienia się na O (mówić → mowa)." },
    { id: 105, category: "Ortografia ó/u", front: "Pis_ć → Pisać", back: "Pisać", rule: "A - nie ó ani u." },
    { id: 106, category: "Ortografia ó/u", front: "Czyt_ć → Czytać", back: "Czytać", rule: "A - nie ó ani u." },
    { id: 107, category: "Ortografia ó/u", front: "Słuch_ć → Słuchać", back: "Słuchać", rule: "A - nie ó ani u." },
    { id: 108, category: "Ortografia ó/u", front: "Widz_ć → Widzieć", back: "Widzieć", rule: "E - nie ó ani u." },
    { id: 109, category: "Ortografia ó/u", front: "Słysz_ć → Słyszeć", back: "Słyszeć", rule: "E - nie ó ani u." },
    { id: 110, category: "Ortografia ó/u", front: "R_bić", back: "Robić", rule: "O - nie ó ani u." },
    { id: 111, category: "Ortografia ó/u", front: "Kupi_ć → Kupić", back: "Kupić", rule: "I - nie ó ani u." },
    { id: 112, category: "Ortografia ó/u", front: "Sprzed_ć → Sprzedać", back: "Sprzedać", rule: "A - nie ó ani u." },
    { id: 113, category: "Ortografia ó/u", front: "K_pić", back: "Kąpać → Kópić", rule: "Ą - nie ó ani u." },
    { id: 114, category: "Ortografia ó/u", front: "Myć / M_ć", back: "Myć", rule: "Y - nie ó ani u." },
    { id: 115, category: "Ortografia ó/u", front: "Prać / Pr_ć", back: "Prać", rule: "A - nie ó ani u." },
    { id: 116, category: "Ortografia ó/u", front: "Gotow_ć → Gotować", back: "Gotować", rule: "A - nie ó ani u." },
    { id: 117, category: "Ortografia ó/u", front: "Sm_żyć → Smażyć", back: "Smażyć", rule: "A - nie ó ani u." },
    { id: 118, category: "Ortografia ó/u", front: "Piec / P_c", back: "Piec", rule: "E - nie ó ani u." },
    { id: 119, category: "Ortografia ó/u", front: "Gr_ć → Grać", back: "Grać", rule: "A - nie ó ani u." },
    { id: 120, category: "Ortografia ó/u", front: "Śpiew_ć → Śpiewać", back: "Śpiewać", rule: "A - nie ó ani u." },

    // === ORTOGRAFIA rz/ż (60 cards) ===
    { id: 121, category: "Ortografia rz/ż", front: "P_zygoda", back: "Przygoda", rule: "Po P piszemy RZ." },
    { id: 122, category: "Ortografia rz/ż", front: "Dob_ze", back: "Dobrze", rule: "Po B piszemy RZ." },
    { id: 123, category: "Ortografia rz/ż", front: "_zeka", back: "Rzeka", rule: "RZ wymienia się na R (rzeka → rzeczny)." },
    { id: 124, category: "Ortografia rz/ż", front: "Ksią_ka", back: "Książka", rule: "Ż wymienia się na G (książka → księgi)." },
    { id: 125, category: "Ortografia rz/ż", front: "In_ynier", back: "Inżynier", rule: "Po N piszemy Ż." },
    { id: 126, category: "Ortografia rz/ż", front: "Ch_zan", back: "Chrzan", rule: "Po CH piszemy RZ." },
    { id: 127, category: "Ortografia rz/ż", front: "Uj_zeć", back: "Ujrzeć", rule: "Po J piszemy RZ." },
    { id: 128, category: "Ortografia rz/ż", front: "Wie_a", back: "Wieża", rule: "Ż wymienia się na G (wieża → wieżyca)." },
    { id: 129, category: "Ortografia rz/ż", front: "Mo_e", back: "Może", rule: "Ż wymienia się na G (może → możliwy)." },
    { id: 130, category: "Ortografia rz/ż", front: "G_eszny", back: "Grzeszny", rule: "RZ wymienia się na R (grzeszny → grzech)." },
    { id: 131, category: "Ortografia rz/ż", front: "Mo_liwy", back: "Możliwy", rule: "Ż wymienia się na G (możliwy → może)." },
    { id: 132, category: "Ortografia rz/ż", front: "Gro_ny", back: "Groźny", rule: "Ź wymienia się na Z (groźny → groza)." },
    { id: 133, category: "Ortografia rz/ż", front: "Wie_yca", back: "Wieżyca", rule: "Ż wymienia się na G." },
    { id: 134, category: "Ortografia rz/ż", front: "P_ebiśnieg", back: "Przebiśnieg", rule: "Po P piszemy RZ." },
    { id: 135, category: "Ortografia rz/ż", front: "T_zeba", back: "Trzeba", rule: "Po T piszemy RZ." },
    { id: 136, category: "Ortografia rz/ż", front: "Ma_z", back: "Marzec", rule: "RZ wymienia się na R (marzec → marca)." },
    { id: 137, category: "Ortografia rz/ż", front: "Bu_a", back: "Burza", rule: "RZ wymienia się na R (burza → burzyć)." },
    { id: 138, category: "Ortografia rz/ż", front: "Grzmot / G_zmot", back: "Grzmot", rule: "RZ po G." },
    { id: 139, category: "Ortografia rz/ż", front: "K_ak", back: "Krzak", rule: "RZ po K." },
    { id: 140, category: "Ortografia rz/ż", front: "K_yk", back: "Krzyk", rule: "RZ po K." },
    { id: 141, category: "Ortografia rz/ż", front: "K_esło", back: "Krzesło", rule: "RZ po K." },
    { id: 142, category: "Ortografia rz/ż", front: "K_ew", back: "Krew", rule: "E - nie rz ani ż." },
    { id: 143, category: "Ortografia rz/ż", front: "D_zewo", back: "Drzewo", rule: "RZ po D." },
    { id: 144, category: "Ortografia rz/ż", front: "D_wi", back: "Drzwi", rule: "RZ po D." },
    { id: 145, category: "Ortografia rz/ż", front: "T_zy", back: "Trzy", rule: "RZ po T." },
    { id: 146, category: "Ortografia rz/ż", front: "T_zeci", back: "Trzeci", rule: "RZ po T." },
    { id: 147, category: "Ortografia rz/ż", front: "T_zynaście", back: "Trzynaście", rule: "RZ po T." },
    { id: 148, category: "Ortografia rz/ż", front: "W_zesień", back: "Wrzesień", rule: "RZ po W." },
    { id: 149, category: "Ortografia rz/ż", front: "W_zucić", back: "Wrzucić", rule: "RZ po W." },
    { id: 150, category: "Ortografia rz/ż", front: "W_awa", back: "Wrzawa", rule: "RZ po W." },
    { id: 151, category: "Ortografia rz/ż", front: "P_yjaciel", back: "Przyjaciel", rule: "RZ po P." },
    { id: 152, category: "Ortografia rz/ż", front: "P_yjemny", back: "Przyjemny", rule: "RZ po P." },
    { id: 153, category: "Ortografia rz/ż", front: "P_yjść", back: "Przyjść", rule: "RZ po P." },
    { id: 154, category: "Ortografia rz/ż", front: "P_yjąć", back: "Przyjąć", rule: "RZ po P." },
    { id: 155, category: "Ortografia rz/ż", front: "P_yjechać", back: "Przyjechać", rule: "RZ po P." },
    { id: 156, category: "Ortografia rz/ż", front: "P_yjazd", back: "Przyjazd", rule: "RZ po P." },
    { id: 157, category: "Ortografia rz/ż", front: "P_yjemność", back: "Przyjemność", rule: "RZ po P." },
    { id: 158, category: "Ortografia rz/ż", front: "P_yjęcie", back: "Przyjęcie", rule: "RZ po P." },
    { id: 159, category: "Ortografia rz/ż", front: "P_ypomnieć", back: "Przypomnieć", rule: "RZ po P." },
    { id: 160, category: "Ortografia rz/ż", front: "P_ypadek", back: "Przypadek", rule: "RZ po P." },
    { id: 161, category: "Ortografia rz/ż", front: "P_ynieść", back: "Przynieść", rule: "RZ po P." },
    { id: 162, category: "Ortografia rz/ż", front: "P_yroda", back: "Przyroda", rule: "RZ po P." },
    { id: 163, category: "Ortografia rz/ż", front: "P_yszły", back: "Przyszły", rule: "RZ po P." },
    { id: 164, category: "Ortografia rz/ż", front: "P_yszłość", back: "Przyszłość", rule: "RZ po P." },
    { id: 165, category: "Ortografia rz/ż", front: "P_ygotować", back: "Przygotować", rule: "RZ po P." },
    { id: 166, category: "Ortografia rz/ż", front: "P_ykład", back: "Przykład", rule: "RZ po P." },
    { id: 167, category: "Ortografia rz/ż", front: "P_yjazny", back: "Przyjazny", rule: "RZ po P." },
    { id: 168, category: "Ortografia rz/ż", front: "P_yjemnie", back: "Przyjemnie", rule: "RZ po P." },
    { id: 169, category: "Ortografia rz/ż", front: "Ży_afa", back: "Żyrafa", rule: "Ż - wyraz obcy." },
    { id: 170, category: "Ortografia rz/ż", front: "_aba", back: "Żaba", rule: "Ż wymienia się na G (żaba → żabka)." },
    { id: 171, category: "Ortografia rz/ż", front: "_ycie", back: "Życie", rule: "Ż wymienia się na G (życie → żyć)." },
    { id: 172, category: "Ortografia rz/ż", front: "_yć", back: "Żyć", rule: "Ż wymienia się na G." },
    { id: 173, category: "Ortografia rz/ż", front: "_ołnierz", back: "Żołnierz", rule: "Ż wymienia się na G." },
    { id: 174, category: "Ortografia rz/ż", front: "_ona", back: "Żona", rule: "Ż wymienia się na G (żona → żonaty)." },
    { id: 175, category: "Ortografia rz/ż", front: "_ółty", back: "Żółty", rule: "Ż wymienia się na G (żółty → żółtko)." },
    { id: 176, category: "Ortografia rz/ż", front: "_ółw", back: "Żółw", rule: "Ż wymienia się na G." },
    { id: 177, category: "Ortografia rz/ż", front: "_al", back: "Żal", rule: "Ż wymienia się na G (żal → żałować)." },
    { id: 178, category: "Ortografia rz/ż", front: "_art", back: "Żart", rule: "Ż wymienia się na G (żart → żartować)." },
    { id: 179, category: "Ortografia rz/ż", front: "_elazny", back: "Żelazny", rule: "Ż wymienia się na G (żelazny → żelazo)." },
    { id: 180, category: "Ortografia rz/ż", front: "_elazo", back: "Żelazo", rule: "Ż wymienia się na G." },

    // I'll continue in the next part due to length...
];

// Export
if (typeof module !== 'undefined') {
    module.exports = flashcards;
}
